version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache-cli:v6.12.2
    ports:
      - '8545:8545'
    command: '-h 0.0.0.0 -i 5777'
  api:
    build: .
    image: example-truffle-api
    ports:
      - '3000:3000'
    environment:
      - RPC_HOST=ganache
      - RPC_PORT=8545
      - NETWORK_ID=*
    depends_on:
      - ganache

